### ISSUE TITLE
add GPL license

### ISSUE THREAD

**Issue by waymondo** [hlissner/emacs-counsel-css#1]
Hey there again,

This package is great and I would like to submit a recipe for this to MELPA, but I noticed there is no GPL license listed for it. Can you add one so I can submit it?

**Comment by hlissner** [comment]
I'm glad it's useful to you! I've added a LICENSE and boilerplate to counsel-css.el. Thanks for submitting it to MELPA for me!

**Comment by waymondo** [comment]
No problem. This is much better than my painful, insufficient nested scss/less imenu expression. Recipe submitted: https://github.com/melpa/melpa/pull/5323
