### ISSUE TITLE
Add support for stylus-lang

### ISSUE THREAD

**Issue by Brettm12345** [hlissner/emacs-counsel-css#4]
I would really appreciate it if this plugin had support for the [stylus](https://stylus-lang.com/) css pre-processor

**Comment by hlissner** [comment]
Would it simply be a matter of adding `stylus-mode` to [this list](https://github.com/hlissner/emacs-counsel-css/blob/master/counsel-css.el#L209)?

Give this a try:

```elisp
(add-hook 'stylus-mode-hook
          (lambda ()
            (setq imenu-create-index-function 'counsel-css--imenu-create-index-function)))
```

**Comment by hlissner** [comment]
I've removed the major-mode restriction on `counsel-css-imenu-setup`, so you should be able to add it to `stylus-mode-hook` now. Let me know if that isn't enough and I'll reopen the issue.
